

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ratemy_development
  pool: 5
  username: root
  password: indian
  host: localhost


test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ratemy_test
  pool: 5
  username: root
  password: indian
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: ratemy_production
  pool: 5
  username: root
  password: indian
  host: localhost

