
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: newratemy_development
  pool: 5
  username: root
  password: Dillinger420
  host: localhost


test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: newratemy_test
  pool: 5
  username: root
  password: Dillinger420
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: newratemy_production
  pool: 5
  username: root
  password: Dillinger420
  host: localhost

