development: &defaults
  client_id: 10282585370
  client_secret: 96256438e79805bff47bb5fd9af2810f
  scope: user_about_me,user_activities,user_birthday,read_friendlists,read_insights,read_mailbox,read_requests,read_stream,user_education_history,user_events,user_groups,user_hometown,user_interests,user_likes,user_location,user_notes,user_online_presence,user_photo_video_tags,user_photos,user_relationships,user_relationship_details,user_religion_politics,user_status,email,publish_stream,create_event,rsvp_event,friends_hometown,friends_interests,friends_likes,friends_location,friends_notes,friends_online_presence,friends_photo_video_tags,friends_photos,friends_relationships,friends_relationship_details,friends_religion_politics,friends_status

test:
  <<: *defaults

production:
  <<: *defaults